export const cartActionTypes = {
  TOGGLE_DROPDOWN_VISIBILITY: "TOGGLE_DROPDOWN_VISIBILITY",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
};
